import Head from 'next/head';
import MainSection from '../components/main section/MainSection';
import Filter from '../components/main section/Filter';
import ItemsContainer from '../components/main section/ItemsContainer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainSection>
        <Filter />
        <ItemsContainer />
      </MainSection>
    </>
  );
}
